apiVersion: v1  
kind: ReplicationController  
metadata:  
  name: redis-persistence
spec:  
  replicas: 1  
  template:  
    metadata:  
      labels:  
        app: redis 
    spec:  
      nodeSelector:
        infra-service: "false"
      containers:  
      - name: redis 
        image: 172.22.111.199:80/cloud/redis:1.1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "4096Mi"
        ports:  
        - containerPort: 6379 
        volumeMounts:
        - mountPath: "/data"
          name: data
      volumes:
          - name: "data"
            rbd:
              monitors:
              - "10.17.17.9:6789"
              - "10.17.17.10:6789"
              - "10.17.17.11:6789"
              pool: "rbd"
              image: "redis-db"
              user: "admin"
              secretRef:
                name: "ceph-secret"
              keyring: "/etc/ceph/ceph.client.admin.keyring"
              fsType: "ext4"
              readOnly: false
