apiVersion: v1
kind: Pod
metadata:
  name: redis-node1
  labels:
    name: redis
    node: node1
spec:
  containers:
  -
    name: redis
    image: 172.22.111.199:80/cloud/k8s-redis:1.0
    ports:
    - containerPort: 6379
    volumeMounts:
    - mountPath: /data
      name: redis-data
    env:
      - name: MASTER
        value: "1"
  volumes:
    - name: redis-data
      emptyDir: {}
